import 'dart:convert';
import 'package:vyuh_node_flow/vyuh_node_flow.dart';
import 'vpl_nodes.dart';

/// VPL 代码生成器 - 将节点图导出为可执行代码
class VplCodeGenerator {
  final NodeFlowController<VplNodeData, dynamic> controller;

  VplCodeGenerator(this.controller);

  /// 导出为 JSON 格式（可重新导入）
  String exportJson({bool pretty = true}) {
    final graph = controller.exportGraph();
    final nodes = <Map<String, dynamic>>[];
    for (final id in controller.nodeIds) {
      final node = controller.getNode(id);
      if (node == null) continue;
      nodes.add({
        'id': node.id,
        'type': node.type,
        'x': node.position.value.dx,
        'y': node.position.value.dy,
        'data': node.data.toJson(),
        'ports': node.ports
            .map(
              (p) => {
                'id': p.id,
                'name': p.name,
                'position': p.position.name,
                'type': p.type.name,
              },
            )
            .toList(),
      });
    }

    final connections = <Map<String, dynamic>>[];
    for (final conn in graph.connections) {
      connections.add({
        'id': conn.id,
        'sourceNodeId': conn.sourceNodeId,
        'sourcePortId': conn.sourcePortId,
        'targetNodeId': conn.targetNodeId,
        'targetPortId': conn.targetPortId,
      });
    }

    final output = {'version': 1, 'nodes': nodes, 'connections': connections};

    final encoder = pretty
        ? const JsonEncoder.withIndent('  ')
        : const JsonEncoder();
    return encoder.convert(output);
  }

  /// 导出为 Python 代码
  String exportPython() {
    final graph = controller.exportGraph();
    final buf = StringBuffer();
    buf.writeln('# 由 RemindAI VPL 工具自动生成');
    buf.writeln('# Generated by RemindAI VPL Tool');
    buf.writeln();

    // 收集所有节点
    final nodeMap = <String, Node<VplNodeData>>{};
    for (final id in controller.nodeIds) {
      final node = controller.getNode(id);
      if (node != null) nodeMap[id] = node;
    }

    // 构建连接索引: targetNodeId:targetPortId -> sourceNodeId:sourcePortId
    final connIndex = <String, String>{};
    for (final conn in graph.connections) {
      connIndex['${conn.targetNodeId}:${conn.targetPortId}'] =
          '${conn.sourceNodeId}:${conn.sourcePortId}';
    }

    // 找到起始节点
    final startNodes = nodeMap.values
        .where((n) => n.data.nodeType == VplNodeType.start)
        .toList();

    if (startNodes.isEmpty) {
      buf.writeln('# 错误: 没有找到开始节点');
      return buf.toString();
    }

    // 变量声明
    final varNodes = nodeMap.values.where(
      (n) => n.data.nodeType == VplNodeType.variable,
    );
    for (final vn in varNodes) {
      final name = vn.data.properties['name'] ?? 'var_${vn.id.hashCode.abs()}';
      final value = vn.data.properties['value'] ?? 'None';
      buf.writeln('$name = $value');
    }

    // 常量声明
    final constNodes = nodeMap.values.where(
      (n) => n.data.nodeType == VplNodeType.constant,
    );
    for (final cn in constNodes) {
      final name =
          cn.data.properties['name'] ?? 'CONST_${cn.id.hashCode.abs()}';
      final value = cn.data.properties['value'] ?? '0';
      buf.writeln('$name = $value');
    }

    if (varNodes.isNotEmpty || constNodes.isNotEmpty) buf.writeln();

    // 从起始节点沿执行链遍历生成代码
    for (final start in startNodes) {
      _generatePythonChain(buf, start, nodeMap, connIndex, graph, 0);
    }

    return buf.toString();
  }

  void _generatePythonChain(
    StringBuffer buf,
    Node<VplNodeData> node,
    Map<String, Node<VplNodeData>> nodeMap,
    Map<String, String> connIndex,
    NodeGraph<VplNodeData, dynamic> graph,
    int indent,
  ) {
    final pad = '    ' * indent;
    final data = node.data;
    final props = data.properties;

    switch (data.nodeType) {
      case VplNodeType.start:
        // 不产生代码，继续到下一个节点
        break;
      case VplNodeType.end:
        return; // 终止
      case VplNodeType.print:
        final value = _resolveInput(
          node.id,
          'value',
          nodeMap,
          connIndex,
          props,
        );
        buf.writeln('${pad}print($value)');
        break;
      case VplNodeType.input:
        final prompt = props['prompt'] ?? '"请输入: "';
        final varName = props['varName'] ?? 'user_input';
        buf.writeln('$pad$varName = input($prompt)');
        break;
      case VplNodeType.ifCondition:
        final cond = _resolveInput(node.id, 'cond', nodeMap, connIndex, props);
        buf.writeln('${pad}if $cond:');
        // True 分支
        final trueNext = _findNextNode('true_out', node.id, graph);
        if (trueNext != null && nodeMap.containsKey(trueNext)) {
          _generatePythonChain(
            buf,
            nodeMap[trueNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
        } else {
          buf.writeln('$pad    pass');
        }
        // False 分支
        final falseNext = _findNextNode('false_out', node.id, graph);
        if (falseNext != null && nodeMap.containsKey(falseNext)) {
          buf.writeln('${pad}else:');
          _generatePythonChain(
            buf,
            nodeMap[falseNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
        }
        return; // 条件节点自己处理了后续
      case VplNodeType.forLoop:
        final count = _resolveInput(
          node.id,
          'count',
          nodeMap,
          connIndex,
          props,
        );
        final indexVar = props['indexVar'] ?? 'i';
        buf.writeln('${pad}for $indexVar in range($count):');
        final bodyNext = _findNextNode('body', node.id, graph);
        if (bodyNext != null && nodeMap.containsKey(bodyNext)) {
          _generatePythonChain(
            buf,
            nodeMap[bodyNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
        } else {
          buf.writeln('$pad    pass');
        }
        // done 出口继续
        final doneNext = _findNextNode('done', node.id, graph);
        if (doneNext != null && nodeMap.containsKey(doneNext)) {
          _generatePythonChain(
            buf,
            nodeMap[doneNext]!,
            nodeMap,
            connIndex,
            graph,
            indent,
          );
        }
        return;
      case VplNodeType.whileLoop:
        final cond = _resolveInput(node.id, 'cond', nodeMap, connIndex, props);
        buf.writeln('${pad}while $cond:');
        final bodyNext = _findNextNode('body', node.id, graph);
        if (bodyNext != null && nodeMap.containsKey(bodyNext)) {
          _generatePythonChain(
            buf,
            nodeMap[bodyNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
        } else {
          buf.writeln('$pad    pass');
        }
        final doneNext = _findNextNode('done', node.id, graph);
        if (doneNext != null && nodeMap.containsKey(doneNext)) {
          _generatePythonChain(
            buf,
            nodeMap[doneNext]!,
            nodeMap,
            connIndex,
            graph,
            indent,
          );
        }
        return;
      case VplNodeType.math:
        final op = props['op'] ?? '+';
        final a = _resolveInput(node.id, 'a', nodeMap, connIndex, props);
        final b = _resolveInput(node.id, 'b', nodeMap, connIndex, props);
        final resultVar = props['resultVar'] ?? 'result';
        buf.writeln('$pad$resultVar = $a $op $b');
        break;
      case VplNodeType.compare:
        final op = props['op'] ?? '==';
        final a = _resolveInput(node.id, 'a', nodeMap, connIndex, props);
        final b = _resolveInput(node.id, 'b', nodeMap, connIndex, props);
        final resultVar = props['resultVar'] ?? 'cmp_result';
        buf.writeln('$pad$resultVar = $a $op $b');
        break;
      case VplNodeType.logic:
        final op = props['op'] ?? 'and';
        final a = _resolveInput(node.id, 'a', nodeMap, connIndex, props);
        final b = _resolveInput(node.id, 'b', nodeMap, connIndex, props);
        final resultVar = props['resultVar'] ?? 'logic_result';
        buf.writeln('$pad$resultVar = $a $op $b');
        break;
      case VplNodeType.string:
        final op = props['op'] ?? 'concat';
        final input = _resolveInput(
          node.id,
          'input',
          nodeMap,
          connIndex,
          props,
        );
        final arg = _resolveInput(node.id, 'arg', nodeMap, connIndex, props);
        final resultVar = props['resultVar'] ?? 'str_result';
        switch (op) {
          case 'concat':
            buf.writeln('$pad$resultVar = $input + $arg');
            break;
          case 'split':
            buf.writeln('$pad$resultVar = $input.split($arg)');
            break;
          case 'replace':
            buf.writeln(
              '$pad$resultVar = $input.replace($arg, ${props['arg2'] ?? '""'})',
            );
            break;
          case 'upper':
            buf.writeln('$pad$resultVar = $input.upper()');
            break;
          case 'lower':
            buf.writeln('$pad$resultVar = $input.lower()');
            break;
          default:
            buf.writeln('$pad$resultVar = $input');
        }
        break;
      case VplNodeType.readFile:
        final path = _resolveInput(node.id, 'path', nodeMap, connIndex, props);
        final varName = props['varName'] ?? 'file_content';
        buf.writeln('${pad}with open($path, "r", encoding="utf-8") as f:');
        buf.writeln('$pad    $varName = f.read()');
        break;
      case VplNodeType.writeFile:
        final path = _resolveInput(node.id, 'path', nodeMap, connIndex, props);
        final content = _resolveInput(
          node.id,
          'content',
          nodeMap,
          connIndex,
          props,
        );
        buf.writeln('${pad}with open($path, "w", encoding="utf-8") as f:');
        buf.writeln('$pad    f.write($content)');
        break;
      case VplNodeType.functionDef:
        final name = props['name'] ?? 'my_function';
        final params = props['params'] ?? '';
        buf.writeln('${pad}def $name($params):');
        final bodyNext = _findNextNode('body', node.id, graph);
        if (bodyNext != null && nodeMap.containsKey(bodyNext)) {
          _generatePythonChain(
            buf,
            nodeMap[bodyNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
        } else {
          buf.writeln('$pad    pass');
        }
        buf.writeln();
        return;
      case VplNodeType.functionCall:
        final name = props['name'] ?? 'my_function';
        final args = props['args'] ?? '';
        final resultVar = props['resultVar'] ?? '_';
        buf.writeln('$pad$resultVar = $name($args)');
        break;
      case VplNodeType.returnNode:
        final value = _resolveInput(
          node.id,
          'value',
          nodeMap,
          connIndex,
          props,
        );
        buf.writeln('${pad}return $value');
        return;
      case VplNodeType.variable:
      case VplNodeType.constant:
      case VplNodeType.list:
      case VplNodeType.map:
      case VplNodeType.comment:
        break; // 已经在顶部处理或不需要代码
    }

    // 沿 exec_out 继续
    final nextId = _findNextNode('exec_out', node.id, graph);
    if (nextId != null && nodeMap.containsKey(nextId)) {
      _generatePythonChain(
        buf,
        nodeMap[nextId]!,
        nodeMap,
        connIndex,
        graph,
        indent,
      );
    }
  }

  String _resolveInput(
    String nodeId,
    String portId,
    Map<String, Node<VplNodeData>> nodeMap,
    Map<String, String> connIndex,
    Map<String, dynamic> props,
  ) {
    // 检查是否有连接输入
    final key = '$nodeId:$portId';
    if (connIndex.containsKey(key)) {
      final source = connIndex[key]!;
      final parts = source.split(':');
      final srcNode = nodeMap[parts[0]];
      if (srcNode != null) {
        final srcData = srcNode.data;
        if (srcData.nodeType == VplNodeType.variable ||
            srcData.nodeType == VplNodeType.constant) {
          return srcData.properties['name'] ?? 'None';
        }
        if (srcData.nodeType == VplNodeType.math ||
            srcData.nodeType == VplNodeType.compare ||
            srcData.nodeType == VplNodeType.logic ||
            srcData.nodeType == VplNodeType.string) {
          return srcData.properties['resultVar'] ?? 'result';
        }
        return srcData.properties['name'] ?? srcNode.id;
      }
    }
    // 回退到属性内联值
    return props[portId]?.toString() ?? props['value']?.toString() ?? 'None';
  }

  String? _findNextNode(
    String portId,
    String nodeId,
    NodeGraph<VplNodeData, dynamic> graph,
  ) {
    for (final conn in graph.connections) {
      if (conn.sourceNodeId == nodeId && conn.sourcePortId == portId) {
        return conn.targetNodeId;
      }
    }
    return null;
  }

  /// 导出为 Dart 代码
  String exportDart() {
    final graph = controller.exportGraph();
    final buf = StringBuffer();
    buf.writeln('// 由 RemindAI VPL 工具自动生成');
    buf.writeln('// Generated by RemindAI VPL Tool');
    buf.writeln();
    buf.writeln("import 'dart:io';");
    buf.writeln();
    buf.writeln('void main() {');

    final nodeMap = <String, Node<VplNodeData>>{};
    for (final id in controller.nodeIds) {
      final node = controller.getNode(id);
      if (node != null) nodeMap[id] = node;
    }

    final connIndex = <String, String>{};
    for (final conn in graph.connections) {
      connIndex['${conn.targetNodeId}:${conn.targetPortId}'] =
          '${conn.sourceNodeId}:${conn.sourcePortId}';
    }

    final startNodes = nodeMap.values
        .where((n) => n.data.nodeType == VplNodeType.start)
        .toList();

    if (startNodes.isEmpty) {
      buf.writeln('  // 错误: 没有找到开始节点');
    } else {
      for (final start in startNodes) {
        _generateDartChain(buf, start, nodeMap, connIndex, graph, 1);
      }
    }

    buf.writeln('}');
    return buf.toString();
  }

  void _generateDartChain(
    StringBuffer buf,
    Node<VplNodeData> node,
    Map<String, Node<VplNodeData>> nodeMap,
    Map<String, String> connIndex,
    NodeGraph<VplNodeData, dynamic> graph,
    int indent,
  ) {
    final pad = '  ' * indent;
    final data = node.data;
    final props = data.properties;

    switch (data.nodeType) {
      case VplNodeType.start:
        break;
      case VplNodeType.end:
        return;
      case VplNodeType.print:
        final value = _resolveInput(
          node.id,
          'value',
          nodeMap,
          connIndex,
          props,
        );
        buf.writeln('${pad}print($value);');
        break;
      case VplNodeType.input:
        final prompt = props['prompt'] ?? '"请输入: "';
        final varName = props['varName'] ?? 'userInput';
        buf.writeln('${pad}stdout.write($prompt);');
        buf.writeln('${pad}final $varName = stdin.readLineSync() ?? "";');
        break;
      case VplNodeType.ifCondition:
        final cond = _resolveInput(node.id, 'cond', nodeMap, connIndex, props);
        buf.writeln('${pad}if ($cond) {');
        final trueNext = _findNextNode('true_out', node.id, graph);
        if (trueNext != null && nodeMap.containsKey(trueNext)) {
          _generateDartChain(
            buf,
            nodeMap[trueNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
        }
        buf.writeln('$pad}');
        final falseNext = _findNextNode('false_out', node.id, graph);
        if (falseNext != null && nodeMap.containsKey(falseNext)) {
          buf.writeln('${pad}else {');
          _generateDartChain(
            buf,
            nodeMap[falseNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
          buf.writeln('$pad}');
        }
        return;
      case VplNodeType.forLoop:
        final count = _resolveInput(
          node.id,
          'count',
          nodeMap,
          connIndex,
          props,
        );
        final indexVar = props['indexVar'] ?? 'i';
        buf.writeln(
          '${pad}for (var $indexVar = 0; $indexVar < $count; $indexVar++) {',
        );
        final bodyNext = _findNextNode('body', node.id, graph);
        if (bodyNext != null && nodeMap.containsKey(bodyNext)) {
          _generateDartChain(
            buf,
            nodeMap[bodyNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
        }
        buf.writeln('$pad}');
        final doneNext = _findNextNode('done', node.id, graph);
        if (doneNext != null && nodeMap.containsKey(doneNext)) {
          _generateDartChain(
            buf,
            nodeMap[doneNext]!,
            nodeMap,
            connIndex,
            graph,
            indent,
          );
        }
        return;
      case VplNodeType.whileLoop:
        final cond = _resolveInput(node.id, 'cond', nodeMap, connIndex, props);
        buf.writeln('${pad}while ($cond) {');
        final bodyNext = _findNextNode('body', node.id, graph);
        if (bodyNext != null && nodeMap.containsKey(bodyNext)) {
          _generateDartChain(
            buf,
            nodeMap[bodyNext]!,
            nodeMap,
            connIndex,
            graph,
            indent + 1,
          );
        }
        buf.writeln('$pad}');
        final doneNext = _findNextNode('done', node.id, graph);
        if (doneNext != null && nodeMap.containsKey(doneNext)) {
          _generateDartChain(
            buf,
            nodeMap[doneNext]!,
            nodeMap,
            connIndex,
            graph,
            indent,
          );
        }
        return;
      case VplNodeType.math:
        final op = props['op'] ?? '+';
        final a = _resolveInput(node.id, 'a', nodeMap, connIndex, props);
        final b = _resolveInput(node.id, 'b', nodeMap, connIndex, props);
        final resultVar = props['resultVar'] ?? 'result';
        buf.writeln('${pad}final $resultVar = $a $op $b;');
        break;
      default:
        break;
    }

    final nextId = _findNextNode('exec_out', node.id, graph);
    if (nextId != null && nodeMap.containsKey(nextId)) {
      _generateDartChain(
        buf,
        nodeMap[nextId]!,
        nodeMap,
        connIndex,
        graph,
        indent,
      );
    }
  }
}
